name: Discord Notification

on:
  push:
    branches:
      - "**"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Embed
        env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "🚀 New Push",
              "color": 5814783,
              "fields": [
                {"name": "Author", "value": "${{ github.actor }}", "inline": true},
                {"name": "Branch", "value": "${{ github.ref_name }}", "inline": true},
                {"name": "Repository", "value": "${{ github.repository }}", "inline": false},
                {"name": "Commit", "value": "${{ github.event.head_commit.message }}", "inline": false}
              ]
            }]
          }' \
          $DISCORD_WEBHOOK
